# Site Info
title: Michalis Stavridis
description: Portfolio of an Operations Manager & Data Analyst bridging Industrial Operations with Modern Analytics and Automation
email: m_stavridis@yahoo.com  # Using your actual email from CV
# GitHub Pages Theme
remote_theme: murraco/jekyll-theme-minimal-resume
# Personal Details
username: Michalis Stavridis
user_title: Operations Manager & Data Analyst 
user_description: >
  By day, I improve industrial processes and lead quality improvements at renewable projects. By night, I look into the connection between engineering and analytics.

  I am currently interested in how data science can affect other areas, such as maintenance forecasts and quality improvement. My GitHub features projects that include targeted case studies in industrial and renewable energy data.

# Social Links (only usernames/handles)
linkedin_username: michalis-stavridis-52ba75109
github_username: michstavridis
# Optional exclusions
exclude: ['package.json', 'src', 'node_modules', 'vendor']