# Site Info
title: Michalis Stavridis
description: Data Analyst & Engineer Portfolio
email: m_stavridis@yahoo.com  # <-- Replace with your real email

# GitHub Pages Theme
remote_theme: murraco/jekyll-theme-minimal-resume

# Personal Details
username: Michalis Stavridis
user_title: Data & Project Professional
user_description: >
  Data Analyst and Operations Manager in the renewable energy sector. 
  Focused on driving efficiency through data-driven decision making.

# Social Links (only usernames/handles)
linkedin_username: michalis-stavridis-52ba75109
github_username: michstavridis

# Optional exclusions
exclude: ['package.json', 'src', 'node_modules', 'vendor']